/*
 * TimerCfg.h
 *
 *  Created on: Jun 30, 2022
 *      Author: Eng hadeer
 */

#ifndef MCAL_TIMER_TIMERCFG_H_
#define MCAL_TIMER_TIMERCFG_H_
/*
 *   choose Timer 0 Mode :
 *   TIMER0_NORMAL_MODE
 *   TIMER0_CTC_MODE
 *   TIMER0_FAST_PWM_MODE
 *   TIMER0_PHASE_CORRECT_MODE
 */
#define TIMER0_MODE   TIMER0_FAST_PWM_MODE


/*
 * Normal Mode :
 *  TIMER0_OC0_MODE_DISCONNECTED
    TIMER0_OC0_MODE_TOG
    TIMER0_OC0_MODE_CLR
    TIMER0_OC0_MODE_SET

    Fast PWM :
     TIMER0_OC0_FAST_INVERTED
     TIMER0_OC0_FAST_NONINVERTED

	Phase PWM :
	TIMER0_OC0_PHASE_INVERTED
	TIMER0_OC0_PHASE_NONINVERTED
 */


#define TIMER0_OC0_MODE  TIMER0_OC0_PHASE_NONINVERTED

/*
 * choose Timer 0 Mode :
 * TIMER0_NO_CLOCK
   TIMER0_NO_PRESCALER
   TIMER0_PRESCALER_8
   TIMER0_PRESCALER_64
   TIMER0_PRESCALER_256
   TIMER0_PRESCALER_1024
   TIMER0_PRESCALER_EXT_CLK_FALL_EDGE
   TIMER0_PRESCALER_EXT_CLK_RAIS_EDGE
 */
#define TIMER0_PRESCALLER  TIMER0_PRESCALER_8



#endif /* MCAL_TIMER_TIMERCFG_H_ */
